name: Artifacts Building

on:
    push:
    create:
    
jobs:
    build:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            
            - name: Checkout dependecies
              run: sudo apt update && sudo apt install -y gcc nasm
            
            - name: Checkout permissions
              run: chmod udo+x ./compile.sh
                 
            - name: Build artifacts
              run: sudo ./compile.sh
