name: Artifacts Building

on:
    push:
    create:
    
jobs:
    build:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            
            - name: Checkout dependecies
              run: sudo apt update && sudo apt install -y gcc nasm bc
            
            - name: Checkout permissions
              run: chmod ugo+x ./compile.sh
         
            - name: List files
              run: |
                ls -la
                cat compile.sh
                 
            - name: Build artifacts
              run: sudo bash compile.sh
