name: Artifacts Building

on:
    push:
    create:
    
jobs:
    build:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            - name: Hello
              run: pwd; ls -la
