name: Artifacts Building

on:
    push:
    create:
    
jobs:
    build:
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v1
            
            - name: Checkout dependecies
              run: sudo apt update && sudo apt install -y gcc nasm bc grub
            
            - name: Checkout permissions
              run: chmod ugo+x ./compile.sh
                 
            - name: Build artifacts
              run: sudo bash compile.sh
            
            - name: Checkout artifacts
              run: test -f hdd.img && pwd && ls -la hdd.img
              
            - name: Save boot image
              uses: actions/upload-artifact@v1
              with:
                name: hdd.img
                path: ${{runner.workspace}}/hdd.img
